keys:
    - &markus age1kztzrwvkpyx8ss4qvdtg6rzmzxymlst420dsatd02m8z070paq6qcau36g
creation_rules:
    - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
      key_groups:
          - age:
                - *markus
