# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
  #boot.initrd.kernelModules = ["nvidia"];
  boot.kernelModules = [ "kvm-intel" ];
  #boot.extraModulePackages = [config.boot.kernelPackages.lenovo-legion-module config.boot.kernelPackages.nvidia_x11];
  boot.extraModulePackages = [config.boot.kernelPackages.lenovo-legion-module];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/98dbcbae-b3fb-4aea-92bb-f77995c8a9ca";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."luks-1612b357-1e58-47c0-87bf-46432593c116".device = "/dev/disk/by-uuid/1612b357-1e58-47c0-87bf-46432593c116";

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/5637-455D";
      fsType = "vfat";
    };

  fileSystems."/media/windows" =
    { device = "/dev/disk/by-uuid/7A08D86E08D82B41";
      fsType = "ntfs-3g";
      options = [ "noatime" "uid=1000" "gid=100" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp118s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
